// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP14
#define I2C1_SCL_PIN GP15
#define I2C1_CLOCK_SPEED 400000
#define OLED_DISPLAY_128X32
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_TIMEOUT 30000
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 64
#define RGB_MATRIX_DEFAULT_VAL 32
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_LED_FLUSH_LIMIT 20
#define GOOBER_LED_POWER GP9
#define TAPPING_TERM 200
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
